name: wip-android

run-name: ${{ github.actor }}-android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: install-library
        run: yarn install

      - name: get-required-file
        run: |
          echo ${{ secrets.KEY_STORE }} > ./android/app/wip240524.jks.bs64
          base64 -d ./android/app/wip240524.jks.bs64 > ./android/app/wip240524.jks

      - name: build-apk
        run: npm run apk
      - uses: actions/upload-artifact@v3

      - name: build-aab
        run: npm run aab
      - uses: actions/upload-artifact@v3
