name: wip-android

run-name: ${{ github.actor }}-android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: install-library
        run: npm install

      - name: get-key-store
        run: |
          echo "${{ secrets.KEY_STORE }}" > ./android/app/wip240524.jks.bs64
          base64 -d ./android/app/wip240524.jks.bs64 > ./android/app/wip240524.jks

      - name: get-config
        run: |
          mkdir ./env
          cat <<EOL > ./env/.env
          RESOURCE_AES_KEY="${{ secrets.RESOURCE_AES_KEY }}"
          RESOURCE_AES_IV="${{ secrets.RESOURCE_AES_IV }}"

          GOOGLE_CLOUD_RSA_PUB_KEY="${{ secrets.GOOGLE_CLOUD_RSA_PUB_KEY }}"
          GOOGLE_CLOUD_INIT_INFO_URL="${{ secrets.GOOGLE_CLOUD_INIT_INFO_URL }}"
          GOOGLE_CLOUD_DL_SERVER_URL="${{ secrets.GOOGLE_CLOUD_DL_SERVER_URL }}"

          CLOUD_FLARE_RESOURCE_DOWNLOAD_URL="${{ secrets.CLOUD_FLARE_RESOURCE_DOWNLOAD_URL }}"
          CLOUD_FLARE_RESOURCE_BUCKET="${{ secrets.CLOUD_FLARE_RESOURCE_BUCKET }}"
          CLOUD_FLARE_TOKEN_VALUE="${{ secrets.CLOUD_FLARE_TOKEN_VALUE }}"
          CLOUD_FLARE_ACCESS_KEY_ID="${{ secrets.CLOUD_FLARE_ACCESS_KEY_ID }}"
          CLOUD_FLARE_SECRET_ACCESS_KEY="${{ secrets.CLOUD_FLARE_SECRET_ACCESS_KEY }}"

          GET_DRUG_PRDT_PRMSN_DTL_INQ="${{ secrets.GET_DRUG_PRDT_PRMSN_DTL_INQ }}"
          DRUG_PRDT_PRMSN_INFO_SERVICE="${{ secrets.DRUG_PRDT_PRMSN_INFO_SERVICE }}"
          PERM_ENC_SERVICE_KEY="${{ secrets.PERM_ENC_SERVICE_KEY }}"
          PERM_DEC_SERVICE_KEY="${{ secrets.PERM_DEC_SERVICE_KEY }}"
          EOL
          echo "${{ secrets.ENV_PRODUCTION }}" > env/.env.production

      - name: build-apk
        run: npm run apk
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./android/app/build/outputs/apk/product/release

      - name: build-aab
        run: npm run aab
      - uses: actions/upload-artifact@v4
        with:
          name: aab
          path: ./android/app/build/outputs/bundle/productRelease
