name: wip-android

run-name: wip-android-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: setup-nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install-dependencies
        run: |
          sudo apt install -y jq
          npm install -g eas-cli
          yarn install

      - name: authenticate-expo
        run: |
          eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: get-key-store
        run: |
          echo "${{ secrets.KEY_STORE }}" > ./android/app/wip240524.jks.bs64
          base64 -d ./android/app/wip240524.jks.bs64 > ./android/app/wip240524.jks

      - name: versioning
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          yarn run rebuild
          eas build -p android --profile production
          mv ./android/app/build/outputs/apk/product/release/app-product-release.apk ./app/build/outputs/apk/product/release/wip-$VERSION-${{ github.run_number }}.apk
          mv ./android/app/build/outputs/bundle/productRelease/app-product-release.aab ./app/build/outputs/bundle/productRelease/wip-$VERSION-${{ github.run_number }}.aab

      - uses: actions/upload-artifact@v4
        with:
          name: wip-${{ env.VERSION  }}-${{ github.run_number }}
          path: |
            ./android/app/build/outputs/apk/product/release/wip-${{ env.VERSION  }}-${{ github.run_number }}.apk
            ./android/app/build/outputs/bundle/productRelease/wip-${{ env.VERSION  }}-${{ github.run_number }}.aab
