name: wip-android

run-name: wip-android-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: setup-nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: cache-yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install-dependencies
        run: |
          npm install -g eas-cli
          echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
          echo "YARN_ENABLE_IMMUTABLE_INSTALLS=true" >> $GITHUB_ENV
          yarn install --immutable --immutable-cache
        shell: bash

      - name: versioning
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build -p android --profile production --non-interactive --json > build.json
          BUILD_URL=$(jq -r '.artifacts.buildUrl' build.json)
          curl -L -o wip-${{ env.VERSION }}-${{ github.run_number }}.aab "$BUILD_URL"

      - uses: actions/upload-artifact@v4
        with:
          name: wip-${{ env.VERSION  }}-${{ github.run_number }}
          path: wip-${{ env.VERSION }}-${{ github.run_number }}.aab
