name: wip-android

run-name: wip-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: main

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: setup-nodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn

      - name: setup-java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: install-dependencies
        run: |
          npm install -g eas-cli
          yarn install

      - name: versioning
        run: |
          VERSION=$(jq -r '.expo.version' app.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build-aab-local
        run: |
          eas build \
            -p android \
            --profile production \
            --local \
            --non-interactive

          cp build/*.aab \
            wip-${{ env.VERSION }}-${{ github.run_number }}.aab

      - name: build-apk-local
        run: |
          eas build \
            -p android \
            --profile production-apk \
            --local \
            --non-interactive

          cp build/*.apk \
            wip-${{ env.VERSION }}-${{ github.run_number }}.apk

      - name: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: wip-${{ env.VERSION }}-${{ github.run_number }}
          path: |
            wip-${{ env.VERSION }}-${{ github.run_number }}.aab
            wip-${{ env.VERSION }}-${{ github.run_number }}.apk
