name: wip-android

run-name: wip-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: main

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: setup-nodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: yarn

      - name: setup-java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: install-dependencies
        run: |
          npm install -g eas-cli
          yarn install --frozen-lockfile

      - name: versioning
        run: |
          VERSION=$(node -e "console.log(require('./app.config').default.expo.version)")
          BUILD=$((100 + ${{ github.run_number }}))

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

          echo "Version: $VERSION"
          echo "Build: $BUILD"

      - name: build-aab-local
        env:
          BUILD: ${{ env.BUILD }}
          EAS_LOCAL_BUILD_SKIP_CLEANUP: 1
        run: |
          eas build \
            -p android \
            --profile production \
            --local \
            --non-interactive

          AAB=$(find . -type f -name "*.aab" | xargs ls -t | head -n 1)

          if [ -z "$AAB" ]; then
            echo "AAB not found"
            exit 1
          fi

          echo "Found: $AAB"

          cp "$AAB" \
            "wip-${VERSION}-${BUILD}.aab"

      - name: build-apk-local
        env:
          BUILD: ${{ env.BUILD }}
          EAS_LOCAL_BUILD_SKIP_CLEANUP: 1
        run: |
          eas build \
            -p android \
            --profile production-apk \
            --local \
            --non-interactive

          APK=$(find . -type f -name "*.apk" | xargs ls -t | head -n 1)

          if [ -z "$APK" ]; then
            echo "APK not found"
            exit 1
          fi

          echo "Found: $APK"

          cp "$APK" \
            "wip-${VERSION}-${BUILD}.apk"

      - name: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: wip-${{ env.VERSION }}-${{ env.BUILD }}
          path: |
            wip-${{ env.VERSION }}-${{ env.BUILD }}.aab
            wip-${{ env.VERSION }}-${{ env.BUILD }}.apk
