name: wip-ios

run-name: wip-ios-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: main

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: setup-nodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: yarn

      - name: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: install-dependencies
        run: |
          npm install -g eas-cli

          if [ ! -d node_modules ]; then
            yarn install --frozen-lockfile
          fi

      - name: cache-cocoapods
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
            ios/Pods
          key: pods-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            pods-${{ runner.os }}-

      - name: setup-cocoapods
        run: |
          sudo gem install cocoapods

      - name: install-pods-if-needed
        run: |
          if [ -d ios ]; then
            cd ios

            if [ ! -d Pods ]; then
              pod install
            fi
          fi

      - name: versioning
        run: |
          VERSION=$(node -e "console.log(require('./app.config').default.expo.version)")
          BUILD=$((100 + ${{ github.run_number }}))

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

          echo "Version: $VERSION"
          echo "Build: $BUILD"

      - name: build-local
        env:
          BUILD: ${{ env.BUILD }}
          EAS_LOCAL_BUILD_SKIP_CLEANUP: 1
        run: |
          eas build \
            -p ios \
            --profile production \
            --local \
            --non-interactive

      - name: collect-artifact
        run: |
          IPA=$(find . -type f -name "*.ipa" | head -n 1)

          if [ -z "$IPA" ]; then
            echo "ipa not found"
            exit 1
          fi

          cp "$IPA" \
            "wip-${VERSION}-${BUILD}.ipa"

      - name: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: wip-${{ env.VERSION }}-${{ env.BUILD }}
          path: |
            wip-${{ env.VERSION }}-${{ env.BUILD }}.ipa
