name: wip-ios-build-test

run-name: ${{ github.actor }}-ios-build-test

on:
  workflow_dispatch:

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn set version berry
          yarn install
          cd ios
          pod install

      - name: Run app
        run: |
          yarn ios
          tail -n 50 /tmp/ios-build.log
